version: 2.1

workflows:
  build-release-deploy:
    jobs:
      - build
      - release-dev:
          requires:
            - build
      - approve-deploy-dev:
          type: approval
          requires:
            - release-dev
      - deploy-dev:
          requires:
            - approve-deploy-dev
      - release-qct:
          requires:
            - build
      - approve-deploy-qct:
          type: approval
          requires:
            - release-qct
      - deploy-qct:
          requires:
            - approve-deploy-qct

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
  release-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "release-dev"
          command: "echo This should be releasing to DEV"
  deploy-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "deploy-dev"
          command: "echo This should be deploying to DEV"
  release-qct:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "release-dev"
          command: "echo This should be releasing to DEV"
  deploy-qct:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "deploy-dev"
          command: "echo This should be deploying to DEV"